name = "tunelipt"
uuid = "b130439e-0552-48bd-990b-14b094852d73"
repo = "https://github.com/tunelipt/LocalRegistry"
description = "Registro de pacotes do t√∫nel de vento"

[packages]
11ef6918-d2a1-4d09-8ff3-a8f27dc47c79 = { name = "WMesa", path = "W/WMesa" }
3679571a-6675-409e-9618-c02a2349284e = { name = "DAQHDF5", path = "D/DAQHDF5" }
39ba7910-02ad-4040-a45c-8568ce053524 = { name = "DAQSimpleScripts", path = "D/DAQSimpleScripts" }
4fb5c015-4516-465f-8a65-a29a7c83b06b = { name = "Scanivalve", path = "S/Scanivalve" }
5fb171b4-8a69-45d3-9db0-72e8edc7ce8b = { name = "BuildingGeometry", path = "B/BuildingGeometry" }
7b03aed3-9854-4651-ba28-76b88bef8818 = { name = "DAQCore", path = "D/DAQCore" }
c6aa20e7-78fc-4f60-9f81-ec1aa3f236b0 = { name = "RoboSimples", path = "R/RoboSimples" }
d5de4fbe-640e-469d-b7ad-3c69fc3f3f61 = { name = "Hotwire", path = "H/Hotwire" }
e2b5b24c-ed1b-4dfa-a7f0-df40ce9b2526 = { name = "DTCInitium", path = "D/DTCInitium" }
