name = "tunelipt"
uuid = "b130439e-0552-48bd-990b-14b094852d73"
repo = "https://github.com/tunelipt/LocalRegistry"
description = "Registro de pacotes do t√∫nel de vento"

[packages]
5fb171b4-8a69-45d3-9db0-72e8edc7ce8b = { name = "BuildingGeometry", path = "B/BuildingGeometry" }
7b03aed3-9854-4651-ba28-76b88bef8818 = { name = "DAQCore", path = "D/DAQCore" }
